# Configuration pour Streamlit Cloud
# À MODIFIER après déploiement de l'API sur GCP

API_URL = "https://my-content-api-41998741998.europe-west1.run.app/"

# Note: Remplacez XXXXXXXXX par votre vrai URL Cloud Run